### ISSUE TITLE
Issue when sending a code snippet with an antislash

### ISSUE THREAD

**Issue by rrajkomar** [b-sharpe/SlackStorm#11]
sending a piece of code which has an antislash in it doesn't work :

ex : 

try {
echo 'Yes';
} catch(\Exception $e) {
echo 'No';
}

will not work

**Comment by b-sharpe** [comment]
This is fixed in latest release from 51957afcb1130951bc4c1a3921c35d41423f3d6d.

Plugin should update right from IDE, but can grab it here as well: https://plugins.jetbrains.com/plugin/8014?pr=idea_ce

**Comment by rrajkomar** [comment]
Hi,

I just upgraded my plugin this morning and there's still an issue although it is not with the antislash anymore.
Here a code snippet to test it with :
`throw new \Exception("This will not work");`

It seems the double quotes are the source of the issue now. Trying to send to slack channel without this kind of line of code works fine.

**Comment by b-sharpe** [comment]
You may need to uninstall/reinstall in you IDE, I initially made a mistake in the release and re-released it afterwards.
